In [1]:
import sys,os
if os.path.abspath(os.path.join('..')) not in sys.path:
    sys.path.insert(0, os.path.abspath(os.path.join('..')))

In [2]:
import kerpy

In [3]:
kerpy.diff.lines(size=(7,9)).to_reals()["x"]

array([[ 0.,  0.,  0., -1.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  0.,  1.,  0.,  0.,  0.]], dtype=float32)

In [4]:
kerpy.processing.sharpen()

<kerpy.Kernel numpy =
[[ 0. -1.  0.]
 [-1.  5. -1.]
 [ 0. -1.  0.]] at 0x233da4806d0>

In [5]:
kerpy.processing.gaussian(normalize=False)

<kerpy.Kernel numpy =
[[0.36787944 0.60653066 0.36787944]
 [0.60653066 1.         0.60653066]
 [0.36787944 0.60653066 0.36787944]] at 0x233da480c70>

In [11]:
import numpy as np
np.array([[1,4,6,4,1],[4,16,24,16,4],[6,24,-476,24,6],[4,16,24,16,4],[1,4,6,4,1]])/256*(-1)

array([[-0.00390625, -0.015625  , -0.0234375 , -0.015625  , -0.00390625],
       [-0.015625  , -0.0625    , -0.09375   , -0.0625    , -0.015625  ],
       [-0.0234375 , -0.09375   ,  1.859375  , -0.09375   , -0.0234375 ],
       [-0.015625  , -0.0625    , -0.09375   , -0.0625    , -0.015625  ],
       [-0.00390625, -0.015625  , -0.0234375 , -0.015625  , -0.00390625]])

In [9]:
kerpy.processing.unsharp((5,5))


<kerpy.Kernel numpy =
[[-0.00296902 -0.01330621 -0.02193823 -0.01330621 -0.00296902]
 [-0.01330621 -0.0596343  -0.09832033 -0.0596343  -0.01330621]
 [-0.02193823 -0.09832033  1.83789718 -0.09832033 -0.02193823]
 [-0.01330621 -0.0596343  -0.09832033 -0.0596343  -0.01330621]
 [-0.00296902 -0.01330621 -0.02193823 -0.01330621 -0.00296902]] at 0x233da47d460>