In [1]:
import sys,os, numpy as np
if os.path.abspath(os.path.join('..')) not in sys.path:
    sys.path.insert(0, os.path.abspath(os.path.join('..')))
import kerpy

In [6]:

l

<kerpy.Kernel numpy =
[[ 0. -1.  0.]
 [-1.  5. -1.]
 [ 0. -1.  0.]] at 0x1d2d4fe1e50>

In [8]:
l = kerpy.processing.laplacian()
l.numpy[1,1] += 1
np.sum(kerpy.processing.sharpen()==l) == 9

NameError: name 'np' is not defined